
DROP TABLE brewery IF EXISTS;
DROP TABLE beer IF EXISTS;

CREATE TABLE brewery (
                         id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                         name VARCHAR,
                         city VARCHAR,
                         state VARCHAR
);

CREATE TABLE beer (
                      id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                      name VARCHAR,
                      description VARCHAR,
                      style VARCHAR,
                      abv FLOAT,
                      brewery_id INTEGER
);

ALTER TABLE beer ADD CONSTRAINT fk_beer_brewery FOREIGN KEY (brewery_id) REFERENCES brewery(id);